In [29]:
import pandas as pd
import numpy as np

In [12]:
tweets_genuine=pd.read_csv('tweets.csv',encoding='latin-1')
tweets_genuine.head()

C:\Users\taran\AppData\Local\Temp\ipykernel_26640\2749775797.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  tweets_genuine=pd.read_csv('tweets.csv',encoding='latin-1')

,id,text,source,user_id,truncated,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,retweeted_status_id,geo,...,favorited,retweeted,possibly_sensitive,num_hashtags,num_urls,num_mentions,created_at,timestamp,crawled_at,updated
0,593932392663912449,RT @morningJewshow: Speaking about Jews and co...,"<a href=""http://tapbots.com/tweetbot"" rel=""nof...",678033.0,NaN,0.0,0.0,NaN,5.939322e+17,NaN,...,NaN,NaN,NaN,0.0,0.0,1.0,Fri May 01 00:18:11 +0000 2015,2015-05-01 02:18:11,2015-05-01 12:57:19,2015-05-01 12:57:19
1,593895316719423488,This age/face recognition thing..no reason pla...,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",678033.0,NaN,0.0,0.0,NaN,0.000000e+00,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,Thu Apr 30 21:50:52 +0000 2015,2015-04-30 23:50:52,2015-05-01 12:57:19,2015-05-01 12:57:19
2,593880638069018624,Only upside of the moment I can think of is th...,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",678033.0,NaN,0.0,0.0,NaN,0.000000e+00,NaN,...,NaN,NaN,NaN,2.0,0.0,0.0,Thu Apr 30 20:52:32 +0000 2015,2015-04-30 22:52:32,2015-05-01 12:57:19,2015-05-01 12:57:19
3,593847955536252928,If you're going to think about+create experien...,"<a href=""http://tapbots.com/tweetbot"" rel=""nof...",678033.0,NaN,0.0,0.0,NaN,0.000000e+00,NaN,...,NaN,NaN,NaN,2.0,0.0,0.0,Thu Apr 30 18:42:40 +0000 2015,2015-04-30 20:42:40,2015-05-01 12:57:19,2015-05-01 12:57:19
4,593847687847350272,Watching a thread on FB about possible future ...,"<a href=""http://tapbots.com/tweetbot"" rel=""nof...",678033.0,NaN,0.0,0.0,NaN,0.000000e+00,NaN,...,NaN,NaN,NaN,0.0,0.0,0.0,Thu Apr 30 18:41:36 +0000 2015,2015-04-30 20:41:36,2015-05-01 12:57:19,2015-05-01 12:57:19

In [15]:
tweets_genuine=tweets_genuine.sample(50000)

In [16]:
tweets_genuine.shape

(50000, 25)

In [17]:
tweets_genuine.columns

Index(['id', 'text', 'source', 'user_id', 'truncated', 'in_reply_to_status_id',
       'in_reply_to_user_id', 'in_reply_to_screen_name', 'retweeted_status_id',
       'geo', 'place', 'contributors', 'retweet_count', 'reply_count',
       'favorite_count', 'favorited', 'retweeted', 'possibly_sensitive',
       'num_hashtags', 'num_urls', 'num_mentions', 'created_at', 'timestamp',
       'crawled_at', 'updated'],
      dtype='object')

In [22]:
tweet_cols = [
    'text',
    'retweet_count',
    'reply_count',
    'favorite_count',
    'num_hashtags',
    'num_urls',
    'num_mentions',
]

In [24]:
df=tweets_genuine[tweet_cols]

In [27]:
df.shape

(50000, 7)

In [37]:
zeros=np.zeros(df.shape[0],int)

In [38]:
zeros.shape

(50000,)

In [39]:
df['target']=zeros

C:\Users\taran\AppData\Local\Temp\ipykernel_26640\1498196897.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['target']=zeros

In [40]:
df.head()

,text,retweet_count,reply_count,favorite_count,num_hashtags,num_urls,num_mentions,target
559056,The reason Democrats don't mind raising your t...,0.0,0.0,0.0,0.0,0.0,0.0,0
2102563,â@frickinhard: DESTROY MY ORGANSâ http://t...,1.0,0.0,1.0,0.0,0.0,1.0,0
1257487,Pork belly with bacon jam and coleslaw http://...,0.0,0.0,0.0,0.0,0.0,0.0,0
672326,RT @FaZe_NameLeSs: Why must my bed feel so com...,6.0,0.0,0.0,0.0,0.0,1.0,0
819928,Welp I guess I'm a bad person then. The questi...,0.0,0.0,0.0,0.0,0.0,0.0,0

In [41]:
df.to_csv('tweets1.csv',index=False)

In [42]:
df=pd.read_csv('tweets.csv',encoding='latin-1')
df.head()

C:\Users\taran\AppData\Local\Temp\ipykernel_26640\2750417043.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('tweets.csv',encoding='latin-1')

,id,text,source,user_id,truncated,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,retweeted_status_id,geo,...,favorited,retweeted,possibly_sensitive,num_hashtags,num_urls,num_mentions,created_at,timestamp,crawled_at,updated
0,532627591686275072,I Pooh - In silenzio 1968 http://t.co/ahvQxUqTws,"<a href=""http://www.facebook.com/twitter"" rel=...",24858289,NaN,0,0,NaN,0,NaN,...,NaN,NaN,NaN,0,1,0,Wed Nov 12 20:14:48 +0000 2014,2014-11-12 21:14:48,2014-11-12 21:44:09,2014-11-12 21:44:09
1,532624255058706432,http://t.co/HyI5EQKz6Q,"<a href=""http://www.facebook.com/twitter"" rel=...",24858289,NaN,0,0,NaN,0,NaN,...,NaN,NaN,NaN,0,1,0,Wed Nov 12 20:01:32 +0000 2014,2014-11-12 21:01:32,2014-11-12 21:44:09,2014-11-12 21:44:09
2,532513524460052480,"Tutti a tavola, con il filetto di baccalÃ . ht...","<a href=""http://www.facebook.com/twitter"" rel=...",24858289,NaN,0,0,NaN,0,NaN,...,NaN,NaN,NaN,0,1,0,Wed Nov 12 12:41:32 +0000 2014,2014-11-12 13:41:32,2014-11-12 21:44:09,2014-11-12 21:44:09
3,532297646669852672,http://t.co/NAHQ4l2pUy,"<a href=""http://www.facebook.com/twitter"" rel=...",24858289,NaN,0,0,NaN,0,NaN,...,NaN,NaN,NaN,0,1,0,Tue Nov 11 22:23:43 +0000 2014,2014-11-11 23:23:43,2014-11-12 21:44:09,2014-11-12 21:44:09
4,532295960807100416,Gold - Spandau Ballet http://t.co/o8ZJHt7Neu,"<a href=""http://www.facebook.com/twitter"" rel=...",24858289,NaN,0,0,NaN,0,NaN,...,NaN,NaN,NaN,0,1,0,Tue Nov 11 22:17:01 +0000 2014,2014-11-11 23:17:01,2014-11-12 21:44:09,2014-11-12 21:44:09

In [44]:
df.shape

(1610034, 25)

In [46]:
fake_tweets=df.sample(50000)

In [48]:
fake_tweets.shape

(50000, 25)

In [50]:
fake_tweets=fake_tweets[tweet_cols]

In [52]:
fake_tweets['target']=np.ones(fake_tweets.shape[0],int)

In [53]:
fake_tweets.head()

,text,retweet_count,reply_count,favorite_count,num_hashtags,num_urls,num_mentions,target
971962,"C'Ã¨ che, se tu mi guardi, nei guai ci finisco...",0,0,5,0,0,0,1
716200,#RT se hai le orecchie.,0,0,0,1,0,0,1
374564,Un motivo per amarti!? Perche' sei ricca. Un m...,1,0,4,0,0,0,1
980339,RETWITTA se anche a te Ã¨ capitato di Dire arr...,1,0,0,0,0,0,1
702035,Il valore di un'opera d'arte si misura dalla q...,0,0,0,0,0,0,1

In [54]:
fake_tweets.to_csv('tweets2.csv',index=False)

### Combining

In [1]:
import pandas as pd
df1=pd.read_csv('tweets1.csv',encoding='latin-1')
df2=pd.read_csv('tweets2.csv',encoding='latin-1')

In [2]:
df=pd.concat([df1,df2],ignore_index=False)

In [3]:
df.head()

,text,retweet_count,reply_count,favorite_count,num_hashtags,num_urls,num_mentions,target
0,The reason Democrats don't mind raising your t...,0.0,0.0,0.0,0.0,0.0,0.0,0
1,Ã¢ÂÂ@frickinhard: DESTROY MY ORGANSÃ¢ÂÂ ht...,1.0,0.0,1.0,0.0,0.0,1.0,0
2,Pork belly with bacon jam and coleslaw http://...,0.0,0.0,0.0,0.0,0.0,0.0,0
3,RT @FaZe_NameLeSs: Why must my bed feel so com...,6.0,0.0,0.0,0.0,0.0,1.0,0
4,Welp I guess I'm a bad person then. The questi...,0.0,0.0,0.0,0.0,0.0,0.0,0

In [4]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

In [5]:
df.head()

,text,retweet_count,reply_count,favorite_count,num_hashtags,num_urls,num_mentions,target
0,- Davvero ti piace quella figa di legno? - SÃ...,0.0,0.0,2.0,0.0,0.0,0.0,1
1,Ognuno vale quanto ciÃÂ² che ricerca. Marco A...,0.0,0.0,1.0,0.0,0.0,0.0,1
2,@Styla73 @stitchsarah glad for this update. If...,0.0,0.0,0.0,0.0,0.0,2.0,0
3,"I geni sono i piÃÂ¹ felici fra i mortali, per...",0.0,0.0,0.0,0.0,0.0,0.0,1
4,Il nuovo profilo Twitter disponibile per tutti...,0.0,0.0,1.0,0.0,1.0,0.0,1

In [6]:
df.to_csv('tweets.csv',index=False)

In [7]:
df.head()

,text,retweet_count,reply_count,favorite_count,num_hashtags,num_urls,num_mentions,target
0,- Davvero ti piace quella figa di legno? - SÃ...,0.0,0.0,2.0,0.0,0.0,0.0,1
1,Ognuno vale quanto ciÃÂ² che ricerca. Marco A...,0.0,0.0,1.0,0.0,0.0,0.0,1
2,@Styla73 @stitchsarah glad for this update. If...,0.0,0.0,0.0,0.0,0.0,2.0,0
3,"I geni sono i piÃÂ¹ felici fra i mortali, per...",0.0,0.0,0.0,0.0,0.0,0.0,1
4,Il nuovo profilo Twitter disponibile per tutti...,0.0,0.0,1.0,0.0,1.0,0.0,1